name: CI Pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Print Greeting
        run: echo "Hello from GitHub Actions!"

      - name: Print current work directory
        run: pwd

      - name: List Repository Files
        run: ls -la

      - name: Find docker 
        run: find . -name docker

      - name: Read Missing File
        run: cat abc.txt
